from distutils.core import setup

setup(
    name='sitralib',
    version='1.0.7',
    py_modules=[
        'sitralib.validators.bcc',
        'sitralib.helpers.fecha',
        'sitralib.helpers.byte',
        'sitralib.helpers.funciones',
        'sitralib.helpers.ordenartrama',
        'sitralib.bitsdealarma',
        'sitralib.bitsdestatusi',
        'sitralib.bitsdestatusii',
        'sitralib.bitsdestatusiii',
        'sitralib.bytedefuncion',
        'sitralib.bytedelamparas',
        'sitralib.bytedestatus',
        'sitralib.consultaestadoenviocomando',
        'sitralib.consultaestadoextendido',
        'sitralib.consultapuestoconteo',
        'sitralib.enviocomando',
        'sitralib.grabacion_eeprom',
        'sitralib.imposicion_fecha_hora',
        'sitralib.reportedestatus',
        'sitralib.respuesta_agenda_anual',
        'sitralib.respuesta_agenda_diaria',
        'sitralib.respuesta_agenda_feriados_especial',
        'sitralib.respuesta_estrucutra_parte_alta',
        'sitralib.respuesta_estrucutra_parte_baja',
        'sitralib.respuesta_funciones',
        'sitralib.respuesta_matriz_conflictos',
        'sitralib.respuesta_preajustes',
        'sitralib.respuesta_programa_tiempos',
        'sitralib.respuesta',
        'sitralib.respuestaconsultagurpoextendido',
        'sitralib.respuestaconsultapuestoconteo',
        'sitralib.respuestaenviocomando',
        'sitralib.respuestaenvioestructurapartealta',
        'sitralib.respuestaestadoenviocomando',
    ],
    author='Agustin Bouillet',
    author_email='agustin.bouillet@gmail.com',
    url='http://www.bouillet.com.ar/',
    description='Libreria SITRA',
    # long_description = """Really long text here."""
)
