from distutils.core import setup

setup(
    name='sitralib',
    version='1.0.11',
    py_modules=[
        'sitralib.validators.bcc',
        'sitralib.helpers.fecha',
        'sitralib.helpers.byte',
        'sitralib.helpers.funciones',
        'sitralib.helpers.ordenar_trama',
        'sitralib.bits_alarma',
        'sitralib.bits_status_i',
        'sitralib.bits_status_ii',
        'sitralib.bits_status_iii',
        'sitralib.byte_funcion',
        'sitralib.byte_lamparas',
        'sitralib.byte_status',
        'sitralib.consulta_estado_envio_comando',
        'sitralib.consulta_estado_extendido',
        'sitralib.consulta_puesto_conteo',
        'sitralib.envio_comando',
        'sitralib.grabacion_eeprom',
        'sitralib.imposicion_fecha_hora',
        'sitralib.reporte_estado',
        'sitralib.respuesta_agenda_anual',
        'sitralib.respuesta_agenda_diaria',
        'sitralib.respuesta_agenda_feriados_especial',
        'sitralib.respuesta_consulta_gurpo_extendido',
        'sitralib.respuesta_consulta_puesto_conteo',
        'sitralib.respuesta_envio_comando',
        'sitralib.respuesta_envio_estructura_parte_alta',
        'sitralib.respuesta_estado_envio_comando',
        'sitralib.respuesta_estrucutra_parte_alta',
        'sitralib.respuesta_estrucutra_parte_baja',
        'sitralib.respuesta_funciones',
        'sitralib.respuesta_matriz_conflictos',
        'sitralib.respuesta_preajustes',
        'sitralib.respuesta_programa_tiempos',
        'sitralib.respuesta',
        'sitralib.referencias'
    ],
    author='Agustin Bouillet',
    author_email='agustin.bouillet@gmail.com',
    url='http://www.bouillet.com.ar/',
    description='Libreria SITRA',
    # long_description = """Really long text here."""
)
